### ISSUE TITLE
Torch 1.X is completely incompatible with all recent versions of all UIs, this is unfortunately useless without proper Torch 2.X support

### ISSUE THREAD

**Issue by Akira13641** [megvii-research/HiDiffusion#10]
XFormers also isn't built properly for various architectures in a compatible way on more recent versions, it would be far better if this had Pytorch hardware-accelerated attention instead

**Comment by YoucanBaby** [comment]
Same question. It does not work on torch 2.x.

**Comment by ShenZhang-Shin** [comment]
You can remove XFormers. It reduces the inference time and memory usage but has no influence on image quality. 
We will conduct hidiffusion on torch 2.x and fix the bug

**Comment by ShenZhang-Shin** [comment]
We test the latest HiDiffusion version and it supports torch 2.x.  Please update HiDiffusion to the latest version

pip3 install hidiffusion -U
