### ISSUE TITLE
What about the optionnal code?

### ISSUE THREAD

**Issue by Quick-Eyed-Sky** [megvii-research/HiDiffusion#14]
To install HiDiffusion with SDXL I see this:

# # Optional. enable_xformers_memory_efficient_attention can save memory usage and increase inference speed. enable_model_cpu_offload and enable_vae_tiling can save memory usage.
# pipe.enable_xformers_memory_efficient_attention()
# pipe.enable_model_cpu_offload()
# pipe.enable_vae_tiling()

What are the differences?
Is the speed gain correlated to a decrease of quality?
Do we have this possibility with other models like Playground?

I'm building a colab.

**Comment by ShenZhang-Shin** [comment]
These are the official tools of diffusers. They do not decrease image quality from my personal experience.
We have integrated hidiffusion into playground, see readme.
