### ISSUE TITLE
Do you support ControlNet in SD 1.5?

### ISSUE THREAD

**Issue by kunamin** [megvii-research/HiDiffusion#15]
It is supported in SDXL, but it doesn't seem to be supported in SD 1.5 according to the code.

If it's not supported, I'm also curious if there are any plans to support it in the future.

**Comment by ShenZhang-Shin** [comment]
We now only support SDXL+controlnet.
We are sorry to say that we have no plans to support SD 1.5+controlnet.

**Comment by kunamin** [comment]
Thank you for replying

**Comment by ljjsimon** [comment]
@ShenZhang-Shin sd 1.5 needs high resolution more than sdxl. please support sd 1.5 + controlnet
