### ISSUE TITLE
Can we add version support for diffusers 0.272?

### ISSUE THREAD

**Issue by smthemex** [megvii-research/HiDiffusion#20]
just  control net pipeline has the following error message
![image](https://github.com/megvii-research/HiDiffusion/assets/138738845/5294e6b4-b500-4659-acc4-eb62143bb60e)
The bottom progress is that I am closing “apply_hidiffusion(pipe)”, the regular Control net pipeline process

I fix this issues 
If “apply_hidiffusion(pipe)” is below pipe.enable_xformers_memory_efficient_attention(),pipe.enable_model_cpu_offload(),pipe.enable_vae_tiling()
                    , using controllnet will result in vector errors. If apply_hidiffusion(pipe) is mentioned above, HiDiffusion. py, the module will import the missing information and add it will done

**Comment by ShenZhang-Shin** [comment]
Yes, I also encounter the error. 
More precisely. If apply_hidiffusion(pipe) is below pipe.enable_model_cpu_offload(), make_diffusers_unet_2d_condition function in hidiffusion will be disabled. This is the cause of error.
I don't know exactly how pipe.enable_model_cpu_offload() works. My solution is to place apply_hidiffusion(pipe) in front of pipe.enable_model_cpu_offload().
