### ISSUE TITLE
Can stable cascade be benefited from this wonderful technology?

### ISSUE THREAD

**Issue by DragonQuix** [megvii-research/HiDiffusion#5]
Hi! Your work is great! Can stable cascade be benefited from this wonderful technology?

**Comment by ShenZhang-Shin** [comment]
You can give it a try. We are currently focused on reducing the difficulty of HiDiffusion to enable a broader audience. After we achieve this, we will look into the potential of combining HiDiffusion with Stable Cascade.
If you encounter any difficulties, we can discuss them here.
